<atm city="Сумы" address="" >
    <device type="ATM" latitude="34.767353" longitude="50.940338" fullAddressRu="Украина,область Сумская,город Сумы,улица Ковпака,дом 53,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Ковпака,будинок 53,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kovpaka,building 53,Housing A" placeRu="Магазин " Веселка"" placeUa="Магазин "Веселка"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.797294" longitude="50.906629" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 47,корпус 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 47,корпус 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 47,Housing 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.798362" longitude="50.922195" fullAddressRu="Украина,область Сумская,город Сумы,улица Горького,дом 41" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Горького,будинок 41" fullAddressEn="Ukraine,area Sumska,city Sumy,street Horkoho,building 41" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.816473" longitude="50.900358" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 32/" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 32/" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 32/" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.808036" longitude="50.903883" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 4" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 4" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 4" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.829380" longitude="50.915904" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 41" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 41" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 41" placeRu="ТЦ Атриум" placeUa="ТЦ Атріум" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.789976" longitude="50.911525" fullAddressRu="Украина,область Сумская,город Сумы,улица Ильинская,дом 12/" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Іллінська,будинок 12/" fullAddressEn="Ukraine,area Sumska,city Sumy,street Illinska,building 12/" placeRu="Отделение банка" placeUa="Вiддiлення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.824809" longitude="50.910213" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 22,корпус 1" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 22,корпус 1" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 22,Housing 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.834561" longitude="50.893064" fullAddressRu="Украина,область Сумская,город Сумы,улица Марко Вовчок,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Марка Вовчка,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Marka Vovchka,building 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.828780" longitude="50.916324" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 39,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 39,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 39,Housing A" placeRu="Отделение банка, Зона 24/7" placeUa="Відділення банку, Зона 24/7" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.794503" longitude="50.905107" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 60" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 60" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 60" placeRu="Отделение банка" placeUa="Вiддiлення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.825689" longitude="50.911355" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 22,корпус 1" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 22,корпус 1" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 22,Housing 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.775725" longitude="50.944384" fullAddressRu="Украина,область Сумская,город Сумы,улица Ковпака,дом 11" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Ковпака,будинок 11" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kovpaka,building 11" placeRu="Эко-маркет" placeUa="Еко-маркет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.796243" longitude="50.911991" fullAddressRu="Украина,область Сумская,город Сумы,улица Засумская,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Засумська,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Zasumska,building 1" placeRu="Отделение банка, " Зона24 /7"" placeUa="Відділення банку, "Зона 24/7"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.789343" longitude="50.908578" fullAddressRu="Украина,область Сумская,город Сумы,улица Ярослава Мудрого,дом 57" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Ярослава Мудрого,будинок 57" fullAddressEn="Ukraine,area Sumska,city Sumy,street Yaroslava Mudroho,building 57" placeRu="АТБ-Маркет" placeUa="Супермаркет АТБ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.836692" longitude="50.912826" fullAddressRu="Украина,область Сумская,город Сумы,улица Героев Крут,дом 38,корпус Б" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Героїв Крут,будинок 38,корпус Б" fullAddressEn="Ukraine,area Sumska,city Sumy,street Geroyiv Krut,building 38,Housing B" placeRu="ЕКО-МАРКЕТ" placeUa="Еко-Маркет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.795877" longitude="50.910022" fullAddressRu="Украина,область Сумская,город Сумы,улица Кооперативная,дом 1/" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Кооперативна,будинок 1/" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kooperatyvna,building 1/" placeRu="Универмаг " Киев"" placeUa="Універмаг "Київ"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.804697" longitude="50.904270" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 2/2" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 2/2" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 2/2" placeRu="ТЦ Мануфактура" placeUa="ТЦ Мануфактура" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.779974" longitude="50.879216" fullAddressRu="Украина,область Сумская,город Сумы,улица Герасима Кондратьева,дом 181" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Герасима Кондратьєва,будинок 181" fullAddressEn="Ukraine,area Sumska,city Sumy,street Herasyma Kondratieva,building 181" placeRu="АТБ" placeUa="АТБ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.818998" longitude="50.905002" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 4/1" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 4/1" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 4/1" placeRu="Торговый комплекс  Лавина" placeUa="Торговый комплекс  Лавина" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.789535" longitude="50.901301" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 76" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 76" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 76" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.793775" longitude="50.912312" fullAddressRu="Украина,область Сумская,город Сумы,улица Шевченко,дом 17" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Шевченка,будинок 17" fullAddressEn="Ukraine,area Sumska,city Sumy,street Shevchenka,building 17" placeRu="кафе " Сула"" placeUa="кафе "Сула"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.796172" longitude="50.912294" fullAddressRu="Украина,область Сумская,город Сумы,улица Засумская,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Засумська,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Zasumska,building 1" placeRu="Отделение банка   Зона24 7" placeUa="Відділення банку Зона24 7" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.808305" longitude="50.894731" fullAddressRu="Украина,область Сумская,город Сумы,улица Прокофьева,дом 25" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Прокоф’єва,будинок 25" fullAddressEn="Ukraine,area Sumska,city Sumy,street Prokof’ieva,building 25" placeRu="АМБАР" placeUa="Амбар" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.833628" longitude="50.918258" fullAddressRu="Украина,область Сумская,город Сумы,улица Героев Крут,дом 1/3" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Героїв Крут,будинок 1/3" fullAddressEn="Ukraine,area Sumska,city Sumy,street Geroyiv Krut,building 1/3" placeRu="Гипермаркет Эпицентр" placeUa="Гипермаркет Эпицентр" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.842471" longitude="50.892154" fullAddressRu="Украина,область Сумская,город Сумы,улица Римского-Корсакова,дом 2" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Римського-Корсакова,будинок 2" fullAddressEn="Ukraine,area Sumska,city Sumy,street Rymskoho-Korsakova,building 2" placeRu="Государственный университет" placeUa="Государственный университет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.792535" longitude="50.903110" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 73" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 73" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 73" placeRu="Торговый центр " Атлас"" placeUa="Торгівельний центр "Атлас"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.796232" longitude="50.912155" fullAddressRu="Украина,область Сумская,город Сумы,улица Засумская,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Засумська,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Zasumska,building 1" placeRu="Аптека " Прополис"" placeUa="Аптека "Прополіс"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.776426" longitude="50.941083" fullAddressRu="Украина,область Сумская,город Сумы,улица Курская,дом 111" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Курська,будинок 111" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kurska,building 111" placeRu="Отделение банка" placeUa="Вiддiлення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.794923" longitude="50.910669" fullAddressRu="Украина,область Сумская,город Сумы,улица 1-я Набережная Р.стрелки,дом 10" fullAddressUa="Україна,область Сумська,місто Суми,вулиця 1-А Набережна Р.стрілки,будинок 10" fullAddressEn="Ukraine,area Sumska,city Sumy,street 1-A Naberezhna R.strilky,building 10" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.787170" longitude="50.934146" fullAddressRu="Украина,область Сумская,город Сумы,проспект Курский,дом 39" fullAddressUa="Україна,область Сумська,місто Суми,проспект Курський,будинок 39" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Kurskyi,building 39" placeRu="Магазин  Смак" placeUa="магазин Смак" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.754722" longitude="50.926488" fullAddressRu="Украина,область Сумская,город Сумы,улица Белопольский Путь,дом 19,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Білопільський Шлях,будинок 19,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,street Bilopilskyi Shliakh,building 19,Housing A" placeRu="ВИАНОР" placeUa="ВІАНОР" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.794998" longitude="50.907432" fullAddressRu="Украина,область Сумская,город Сумы,улица Покровская,дом 4" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Покровська,будинок 4" fullAddressEn="Ukraine,area Sumska,city Sumy,street Pokrovska,building 4" placeRu="Магазин " Булочная"" placeUa="Магазин "Булочна"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.803357" longitude="50.910798" fullAddressRu="Украина,область Сумская,город Сумы,площадь Независимости,дом 3,корпус 1" fullAddressUa="Україна,область Сумська,місто Суми,площа Незалежності,будинок 3,корпус 1" fullAddressEn="Ukraine,area Sumska,city Sumy,square Nezalezhnosti,building 3,Housing 1" placeRu="ВИП-ЦЕНТР АКРОПОЛЬ" placeUa="ВІП-ЦЕНТР АКРОПОЛЬ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.770038" longitude="50.914805" fullAddressRu="Украина,область Сумская,город Сумы,улица Степана Бандеры,дом 40" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Степана Бандери,будинок 40" fullAddressEn="Ukraine,area Sumska,city Sumy,street Stepana Banderi,building 40" placeRu="" Модуль"" placeUa=""Модуль"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.806430" longitude="50.918769" fullAddressRu="Украина,область Сумская,город Сумы,проспект Тараса Шевченко,дом 15" fullAddressUa="Україна,область Сумська,місто Суми,проспект Тараса Шевченка,будинок 15" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Tarasa Shevchenka,building 15" placeRu="Общеж.  Машколледжа" placeUa="Общеж.  Машколледжа" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.823124" longitude="50.910926" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 13" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 13" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 13" placeRu="Маг. "100 пудов"" placeUa="Маг. "100 пудов"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.797461" longitude="50.910269" fullAddressRu="Украина,область Сумская,город Сумы,улица Казацкий Вал,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Козацький Вал,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kozatskyi Val,building 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.784600" longitude="50.897456" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 108" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 108" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 108" placeRu="Стройколледж" placeUa="Стройколледж" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.755827" longitude="50.891433" fullAddressRu="Украина,область Сумская,город Сумы,улица Роменская,дом 81" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Роменська,будинок 81" fullAddressEn="Ukraine,area Sumska,city Sumy,street Romenska,building 81" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.831717" longitude="50.889445" fullAddressRu="Украина,область Сумская,город Сумы,улица Марко Вовчок,дом 13,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Марка Вовчка,будинок 13,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,street Marka Vovchka,building 13,Housing A" placeRu="Магазин " Кооператор"" placeUa="Магазин "Кооператор"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.816809" longitude="50.923896" fullAddressRu="Украина,область Сумская,город Сумы,улица Троицкая,дом 48" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Троїцька,будинок 48" fullAddressEn="Ukraine,area Sumska,city Sumy,street Troitska,building 48" placeRu="Банковский модуль" placeUa="Банківський модуль" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.844132" longitude="50.905647" fullAddressRu="Украина,область Сумская,город Сумы,улица Героев Крут,дом 76,корпус 3" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Героїв Крут,будинок 76,корпус 3" fullAddressEn="Ukraine,area Sumska,city Sumy,street Geroyiv Krut,building 76,Housing 3" placeRu="Торговий Центр" placeUa="Торгівельний Центр" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.777070" longitude="50.895829" fullAddressRu="Украина,область Сумская,город Сумы,улица 20-Лет Победы,дом 13" fullAddressUa="Україна,область Сумська,місто Суми,вулиця 20-Років Перемоги,будинок 13" fullAddressEn="Ukraine,area Sumska,city Sumy,street 20-Rokiv Peremohy,building 13" placeRu="Центральная Гор. Больница" placeUa="Центральна Міська Лікарня" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.805010" longitude="50.920736" fullAddressRu="Украина,область Сумская,город Сумы,улица Супруна,дом 9" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Супруна,будинок 9" fullAddressEn="Ukraine,area Sumska,city Sumy,street Supruna,building 9" placeRu="Отделение банка" placeUa="Вiддiлення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.776498" longitude="50.940594" fullAddressRu="Украина,область Сумская,город Сумы,проспект Курский,дом 111" fullAddressUa="Україна,область Сумська,місто Суми,проспект Курський,будинок 111" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Kurskyi,building 111" placeRu="ТЦ " Маячок"" placeUa="ТЦ "Маячок"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.756276" longitude="50.898001" fullAddressRu="Украина,область Сумская,город Сумы,улица Котляревского,дом 3/1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Котляревського,будинок 3/1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kotliarevskoho,building 3/1" placeRu="Магазин " Веселка"" placeUa="Магазин "Веселка"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.814658" longitude="50.878074" fullAddressRu="Украина,область Сумская,город Сумы,улица Санаторная,дом 32" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Санаторна,будинок 32" fullAddressEn="Ukraine,area Sumska,city Sumy,street Sanatorna,building 32" placeRu="Медицинский Институт" placeUa="Медичний Інститут" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.832193" longitude="50.915387" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 46" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 46" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 46" placeRu="Торговый Комплекс " Березка"" placeUa="Торговый Комплекс "Березка"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.815898" longitude="50.917846" fullAddressRu="Украина,область Сумская,город Сумы,улица Троицкая,дом 26" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Троїцька,будинок 26" fullAddressEn="Ukraine,area Sumska,city Sumy,street Troitska,building 26" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.777992" longitude="50.881572" fullAddressRu="Украина,область Сумская,город Сумы,улица Герасима Кондратьева,дом 160" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Герасима Кондратьєва,будинок 160" fullAddressEn="Ukraine,area Sumska,city Sumy,street Herasyma Kondratieva,building 160" placeRu="СНАУ" placeUa="СНАУ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.798403" longitude="50.922121" fullAddressRu="Украина,область Сумская,город Сумы,улица Горького,дом 41" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Горького,будинок 41" fullAddressEn="Ukraine,area Sumska,city Sumy,street Horkoho,building 41" placeRu="аптека " Мед-Сервис"" placeUa="аптека "Мед-Сервіс"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.810693" longitude="50.902666" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 12" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 12" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 12" placeRu="Отделение банка  А-банк" placeUa="Вiддiлення банку  А-Банк" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.772374" longitude="50.938170" fullAddressRu="Украина,область Сумская,город Сумы,улица Новогодняя,дом 8" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Новорічна,будинок 8" fullAddressEn="Ukraine,area Sumska,city Sumy,street Novorichna,building 8" placeRu="АТБ-Маркет" placeUa="Супермаркет АТБ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.805947" longitude="50.920990" fullAddressRu="Украина,область Сумская,город Сумы,проспект Тараса Шевченко,дом 4" fullAddressUa="Україна,область Сумська,місто Суми,проспект Тараса Шевченка,будинок 4" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Tarasa Shevchenka,building 4" placeRu="Отделение банка, АБанк" placeUa="Вiддiлення банку, А-Банк" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.825689" longitude="50.911355" fullAddressRu="Украина,область Сумская,город Сумы,проспект Михаила Лушпы,дом 22,квартира 252" fullAddressUa="Україна,область Сумська,місто Суми,проспект Михайла Лушпи,будинок 22,квартира 252" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Mykhaila Lushpy,building 22,flat 252" placeRu="Отделение А-Банка" placeUa="Відділення А-Банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.783721" longitude="50.887274" fullAddressRu="Украина,область Сумская,город Сумы,улица Герасима Кондратьева,дом 122" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Герасима Кондратьєва,будинок 122" fullAddressEn="Ukraine,area Sumska,city Sumy,street Herasyma Kondratieva,building 122" placeRu="Маркет КОШИК" placeUa="Маркет КОШИК" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.781426" longitude="50.912515" fullAddressRu="Украина,область Сумская,город Сумы,улица Ильинская,дом 49" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Іллінська,будинок 49" fullAddressEn="Ukraine,area Sumska,city Sumy,street Illinska,building 49" placeRu="9-е отделение " УкрПочта"" placeUa="9-е відділення "УкрПошта"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.811764" longitude="50.926744" fullAddressRu="Украина,область Сумская,город Сумы,улица Привокзальная,дом 7а" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Привокзальна,будинок 7а" fullAddressEn="Ukraine,area Sumska,city Sumy,street Pryvokzalna,building 7a" placeRu="ТЦ Вояж" placeUa="ТЦ Вояж" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.829436" longitude="50.911030" fullAddressRu="Украина,область Сумская,город Сумы,улица Интернационалистов,дом 18" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Інтернаціоналістів,будинок 18" fullAddressEn="Ukraine,area Sumska,city Sumy,street Internatsionalistiv,building 18" placeRu="торговый дом " Анна"" placeUa="торгівельный дім "Анна"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.791620" longitude="50.925368" fullAddressRu="Украина,область Сумская,город Сумы,улица Металлургов,дом 13" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Металургів,будинок 13" fullAddressEn="Ukraine,area Sumska,city Sumy,street Metalurhiv,building 13" placeRu="Отделение банка   Зона24 7" placeUa="Відділення банку Зона24 7" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.837651" longitude="50.893370" fullAddressRu="Украина,область Сумская,город Сумы,улица Ахтырская,дом 4,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Охтирська,будинок 4,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,street Okhtyrska,building 4,Housing A" placeRu="АТБ-Маркет" placeUa="АТБ-Маркет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.797461" longitude="50.910269" fullAddressRu="Украина,область Сумская,город Сумы,улица Казацкий Вал,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Козацький Вал,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kozatskyi Val,building 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.835715" longitude="50.894642" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 100" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 100" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 100" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.799926" longitude="50.915160" fullAddressRu="Украина,область Сумская,город Сумы,улица Горького,дом 5,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Горького,будинок 5,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,street Horkoho,building 5,Housing A" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.791581" longitude="50.925355" fullAddressRu="Украина,область Сумская,город Сумы,улица Металлургов,дом 13" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Металургів,будинок 13" fullAddressEn="Ukraine,area Sumska,city Sumy,street Metalurhiv,building 13" placeRu="Отделение банка" placeUa="Вiддiлення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.829146" longitude="50.911567" fullAddressRu="Украина,область Сумская,город Сумы,улица Интернационалистов,дом 21" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Інтернаціоналістів,будинок 21" fullAddressEn="Ukraine,area Sumska,city Sumy,street Internatsionalistiv,building 21" placeRu="Аптека " Добра"" placeUa="Аптека "Добра"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.799692" longitude="50.908737" fullAddressRu="Украина,область Сумская,город Сумы,улица Соборная,дом 33" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Соборна,будинок 33" fullAddressEn="Ukraine,area Sumska,city Sumy,street Soborna,building 33" placeRu="клуб " Невада"" placeUa="клуб "Невада"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.796108" longitude="50.909855" fullAddressRu="Украина,область Сумская,город Сумы,улица Кооперативная,дом 1/" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Кооперативна,будинок 1/" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kooperatyvna,building 1/" placeRu="ЭКО-МАРКЕТ" placeUa="ЕКО-МАРКЕТ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.819057" longitude="50.899406" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 38" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 38" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 38" placeRu="Аптека " Медсервис"" placeUa="Аптека "Медсервіс"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.794464" longitude="50.901708" fullAddressRu="Украина,область Сумская,город Сумы,улица Герасима Кондратьева,дом 25" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Герасима Кондратьєва,будинок 25" fullAddressEn="Ukraine,area Sumska,city Sumy,street Herasyma Kondratieva,building 25" placeRu="Областная прокуратура" placeUa="Обласна прокуратура" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.796189" longitude="50.913127" fullAddressRu="Украина,область Сумская,город Сумы,улица Засумская,дом 2" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Засумська,будинок 2" fullAddressEn="Ukraine,area Sumska,city Sumy,street Zasumska,building 2" placeRu="ЕВРОБАЗАР" placeUa="Євробазар" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.792290" longitude="50.910225" fullAddressRu="Украина,область Сумская,город Сумы,улица Ильинская,дом 7" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Іллінська,будинок 7" fullAddressEn="Ukraine,area Sumska,city Sumy,street Illinska,building 7" placeRu="Аптека Ильинская" placeUa="Аптека Ільїнська" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.758918" longitude="50.894655" fullAddressRu="Украина,область Сумская,город Сумы,улица Роменская,дом 90" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Роменська,будинок 90" fullAddressEn="Ukraine,area Sumska,city Sumy,street Romenska,building 90" placeRu="Аптека" placeUa="Аптека" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.841455" longitude="50.907899" fullAddressRu="Украина,область Сумская,город Сумы,улица Героев Крут,дом 60" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Героїв Крут,будинок 60" fullAddressEn="Ukraine,area Sumska,city Sumy,street Geroyiv Krut,building 60" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.815716" longitude="50.923592" fullAddressRu="Украина,область Сумская,город Сумы,улица Привокзальная,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Привокзальна,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Pryvokzalna,building 1" placeRu="ЭКО-маркет" placeUa="ЕКО-маркет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.808909" longitude="50.897836" fullAddressRu="Украина,область Сумская,город Сумы,улица Прокофьева,дом 14/" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Прокоф’єва,будинок 14/" fullAddressEn="Ukraine,area Sumska,city Sumy,street Prokof’ieva,building 14/" placeRu="ЭКО-маркет" placeUa="ЕКО-маркет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.799835" longitude="50.917796" fullAddressRu="Украина,область Сумская,город Сумы,улица Горького,дом 26" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Горького,будинок 26" fullAddressEn="Ukraine,area Sumska,city Sumy,street Horkoho,building 26" placeRu="Салон мод" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.776498" longitude="50.940594" fullAddressRu="Украина,область Сумская,город Сумы,проспект Курский,дом 111" fullAddressUa="Україна,область Сумська,місто Суми,проспект Курський,будинок 111" fullAddressEn="Ukraine,area Sumska,city Sumy,avenue Kurskyi,building 111" placeRu="ТЦ " Маячок"" placeUa="ТЦ "Маячок"" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.789568" longitude="50.911633" fullAddressRu="Украина,область Сумская,город Сумы,улица Ильинская,дом 12/" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Іллінська,будинок 12/" fullAddressEn="Ukraine,area Sumska,city Sumy,street Illinska,building 12/" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.791895" longitude="50.903494" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 70" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 70" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 70" placeRu="АТБ" placeUa="АТБ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.763223" longitude="50.940832" fullAddressRu="Украина,область Сумская,город Сумы,улица Ковпака,дом 59,корпус 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Ковпака,будинок 59,корпус 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kovpaka,building 59,Housing 1" placeRu="САМ-МАРКЕТ" placeUa="Сам-маркет" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.797294" longitude="50.906629" fullAddressRu="Украина,область Сумская,город Сумы,улица Петропавловская,дом 47/1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Петропавлівська,будинок 47/1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Petropavlivska,building 47/1" placeRu="Отделение банка   Зона24" placeUa="Відділення банку Зона24" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.799926" longitude="50.915160" fullAddressRu="Украина,область Сумская,город Сумы,улица Горького,дом 5,корпус А" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Горького,будинок 5,корпус А" fullAddressEn="Ukraine,area Sumska,city Sumy,street Horkoho,building 5,Housing A" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.826818" longitude="50.897552" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 58а/1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 58а/1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 58a/1" placeRu="АТБ-Маркет" placeUa="Супермаркет АТБ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.795486" longitude="50.914802" fullAddressRu="Украина,область Сумская,город Сумы,улица Засумская,дом 2" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Засумська,будинок 2" fullAddressEn="Ukraine,area Sumska,city Sumy,street Zasumska,building 2" placeRu="ЕВРОБАЗАР" placeUa="Евробазар" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.816518" longitude="50.920526" fullAddressRu="Украина,область Сумская,город Сумы,улица Троицкая,дом 28" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Троїцька,будинок 28" fullAddressEn="Ukraine,area Sumska,city Sumy,street Troitska,building 28" placeRu="Городская Детская Больница" placeUa="Міська Дитяча Лікарня" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.799261" longitude="50.910605" fullAddressRu="Украина,область Сумская,город Сумы,улица Воскресенская,дом 13,корпус 7" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Воскресенська,будинок 13,корпус 7" fullAddressEn="Ukraine,area Sumska,city Sumy,street Voskresenska,building 13,Housing 7" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.778878" longitude="50.882036" fullAddressRu="Украина,область Сумская,город Сумы,улица Герасима Кондратьева,дом 160" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Герасима Кондратьєва,будинок 160" fullAddressEn="Ukraine,area Sumska,city Sumy,street Herasyma Kondratieva,building 160" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.783334" longitude="50.886473" fullAddressRu="Украина,область Сумская,город Сумы,улица Герасима Кондратьева,дом 122" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Герасима Кондратьєва,будинок 122" fullAddressEn="Ukraine,area Sumska,city Sumy,street Herasyma Kondratieva,building 122" placeRu="АМБАР" placeUa="АМБАР" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.811801" longitude="50.921889" fullAddressRu="Украина,область Сумская,город Сумы,улица Леваневского,дом 22" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Леваневського,будинок 22" fullAddressEn="Ukraine,area Sumska,city Sumy,street Levanevskoho,building 22" placeRu="АТБ-МАРКЕТ" placeUa="Супермаркет АТБ" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.797461" longitude="50.910269" fullAddressRu="Украина,область Сумская,город Сумы,улица Казацкий Вал,дом 1" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Козацький Вал,будинок 1" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kozatskyi Val,building 1" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
    <device type="ATM" latitude="34.816500" longitude="50.900404" fullAddressRu="Украина,область Сумская,город Сумы,улица Харьковская,дом 32" fullAddressUa="Україна,область Сумська,місто Суми,вулиця Харківська,будинок 32" fullAddressEn="Ukraine,area Sumska,city Sumy,street Kharkivska,building 32" placeRu="Отделение банка" placeUa="Відділення банку" cityRU="Сумы" cityUA="Суми" cityEN="Sumy" />
</atm>